# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-json
  - id: check-xml
  - id: pretty-format-json
    args:
    - --autofix
    - --indent=4
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-java
    args: [--autofix, --aosp]
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/collective/zpretty
  rev: 3.1.0
  hooks:
  - id: zpretty

- repo: local
  hooks:
  - id: checkstyle
    name: Checkstyle
    entry: mvn checkstyle:check
    language: system
    types: [java]
    pass_filenames: false
  - id: pmd
    name: PMD
    entry: mvn pmd:check
    language: system
    types: [java]
    pass_filenames: false
  - id: spotbugs
    name: SpotBugs
    entry: mvn spotbugs:check
    language: system
    types: [java]
    pass_filenames: false
